import { z } from "zod";

import { MESSAGE_BODY_MAX } from "@/lib/chat/rules";
import {
  calendarDateSchema,
  listingIdSchema,
  PRICE_MAX,
} from "@/lib/validations/listing";

/**
 * Chat input. Ids reuse `listingIdSchema`, the codebase's cuid-shaped id check.
 *
 * WHAT IS NOT HERE: anything that says who the caller is, or which side of a conversation they are
 * on. Both are derived from the session and the conversation row on the server.
 */

const idSchema = listingIdSchema;

/**
 * A message body: CRLF normalized, trimmed, non-empty, bounded.
 *
 * Normalized before the length check, so a message pasted from Windows is not counted as longer than
 * it reads. Rendered as text by React, so no markup survives into the page.
 */
export const messageBodySchema = z
  .string()
  .transform((value) => value.replace(/\r\n?/g, "\n").trim())
  .pipe(
    z
      .string()
      .min(1, { error: "Please write a message." })
      .max(MESSAGE_BODY_MAX, {
        error: `A message can be at most ${MESSAGE_BODY_MAX} characters.`,
      })
  );

export const startConversationSchema = z.object({
  listingId: idSchema,
});

export const sendMessageSchema = z.object({
  conversationId: idSchema,
  body: messageBodySchema,
  /**
   * Generated by the browser, so a retried send is recognisable as the same message rather than a
   * second one - `Message.clientId` is unique per sender. Also how a tab matches its own optimistic
   * message to the realtime echo. Optional because a script or test may not care.
   */
  clientId: z.uuid().optional(),
});

export const markReadSchema = z.object({
  conversationId: idSchema,
});

/** Whole rupees, matching `Booking.totalPrice` (D2). A rental costs something. */
const rentSchema = z
  .number()
  .int({ error: "Amounts are in whole rupees." })
  .min(1, { error: "The rent must be at least Rs 1." })
  .max(PRICE_MAX, { error: "That amount is too high." });

/** A deposit may be zero - waiving it is a legitimate concession. */
const depositSchema = z
  .number()
  .int({ error: "Amounts are in whole rupees." })
  .min(0, { error: "The deposit cannot be negative." })
  .max(PRICE_MAX, { error: "That amount is too high." });

export const proposeOfferSchema = z
  .object({
    conversationId: idSchema,
    /** Set to renegotiate an existing booking; omitted for an offer before any booking. */
    bookingId: idSchema.optional(),
    startDate: calendarDateSchema,
    endDate: calendarDateSchema,
    totalPrice: rentSchema,
    securityDeposit: depositSchema,
  })
  .superRefine((value, ctx) => {
    if (value.endDate < value.startDate) {
      ctx.addIssue({
        code: "custom",
        path: ["endDate"],
        message: "The return date cannot be before the start date.",
      });
    }
  });

export type ProposeOfferInput = z.infer<typeof proposeOfferSchema>;

export const respondToOfferSchema = z.object({
  offerId: idSchema,
  response: z.enum(["accept", "decline"]),
});

export const withdrawOfferSchema = z.object({
  offerId: idSchema,
});

/** Bounds on an administrator's stated reason for reading a conversation. */
export const ADMIN_VIEW_REASON_MIN = 10;
export const ADMIN_VIEW_REASON_MAX = 1000;

export const adminViewConversationSchema = z.object({
  conversationId: idSchema,
  ground: z.object({
    kind: z.enum(["claim", "dispute", "report"]),
    id: idSchema,
  }),
  reason: z
    .string()
    .trim()
    .min(ADMIN_VIEW_REASON_MIN, {
      error: "Please say why you need to read this conversation.",
    })
    .max(ADMIN_VIEW_REASON_MAX),
});
